apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-indexer-cloud-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kb-indexer-cloud-backend
  template:
    metadata:
      labels:
        app: kb-indexer-cloud-backend
    spec: 
      containers:
      - name: kb-indexer-cloud-backend
        image: jorrithk/kb-indexer-cloud-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: token-secret
              key: jwt_key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: token-secret
              key: key

        - name: DASHBOARD_USERNAME
          valueFrom:
            secretKeyRef:
              name: login-secret
              key: username
        - name: DASHBOARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: login-secret
              key: password

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: kb-indexer-cloud-backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: kb-indexer-cloud-backend
