---
- name: deploy individual k8s files
  hosts: localhost
  vars:
    namespace: default
    version: kb-indexer:latest
    deploy_files:
      - templates/flask-deployment.yml
      - templates/mongodb-deployment.yml
      - templates/job-creator-role.yaml
      - templates/job-creator-role-binding.yaml
      - templates/redis_deployment.yml
      - templates/rq-worker-deployment.yml
      - templates/ingress.yaml
      - templates/prometheus-deployment.yml
  tasks:
    - name: "create namespace {{ namespace }}"
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ namespace }}"
        api_version: v1
        state: present

    - name: "deploy {{ item }} to k8s"
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: "{{ item }}"
        kubeconfig: azure-config
      loop: "{{ deploy_files }}"
