version: "3"
services:
  kb_indexer:
    image: qcdis/kb-indexer:latest
    networks:
      - kb-indexer-network
    environment:
      - DATA_DIR=$DATA_DIR
      - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_HOST=dev_deployment_elastic_backend_1:9200
  elastic_backend:
    image: elasticsearch:8.12.1
    networks:
      - kb-indexer-network
    environment:
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_USER=$ELASTICSEARCH_USERNAME
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${PWD}/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    deploy:
      resources:
        limits:
          memory: 1GB
    depends_on:
      - fixsysctl
  fixsysctl: # Some fix because limits are too low by default
    restart: "no"
    privileged: true
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25m
    image: centos:7
    command: "sysctl -w vm.max_map_count=262144"

networks:
  kb-indexer-network: {}

