apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-worker
spec:
  replicas: 1  # TODO maybe more?
  selector:
    matchLabels:
      app: rq-worker
  template:
    metadata:
      labels:
        app: rq-worker
    spec:
      containers:
      - name: rq-worker
        image: python-flask-server  # Use the same image as the Flask app
        imagePullPolicy: IfNotPresent
        command: ["rq", "worker"]
        env:
          - name: REDIS_URL
            value: "redis://redis:6379/0"
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0